version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile # already lives in .devcontainer/
    volumes:
      - .:/workspace:cached # source code
    working_dir: /workspace
    environment:
      PNPM_HOME: /home/dev/.local/share/pnpm
      AWS_PROFILE: patient-studio-dev # redundant but harmless
    command: bash # dev‑container takes over

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: scheduler
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"

volumes:
  pgdata:
    name: patient-studio_pgdata
